macro(add_sub_dir)
    set(os Linux win mac)
    set(cur_os ${CMAKE_SYSTEM_NAME})
    set(isAdd OFF)
    message(${cur_os})
    cmake_parse_arguments(os "${os}" "" "" ${ARGN})
    
    #如果没有传入参数，所有系统都添加
    if(NOT os_Linux AND NOT os_win AND NOT os_mac)
        set(win ON)
        set(Linux ON)
        set(mac ON)
    endif()
    if(os_Linux)
        set(Linux ON)
    endif()
    if(os_win)
        set(win ON)
    endif()
    if(os_mac)
      set(mac ON)
    endif()

    
    message("os_Linux : " ${os_Linux})
    message("os_mac : " ${os_mac})
    message("os_win : " ${os_win})
    message("cur_os : " ${cur_os} )
    message("Linux : " ${Linux})
    message("mac : " ${mac})
    message("win : " ${win})
endmacro(add_sub_dir)